# Generated by Django 2.1.7 on 2019-03-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190326_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name_of_city',
            new_name='name',
        ),
    ]
